# Generated by Django 4.2.7 on 2023-11-09 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auto',
            new_name='Car',
        ),
    ]
